# Generated by Django 4.1.7 on 2023-05-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_user',
        ),
    ]
